README.md, packaging/docker-builder/Dockerfile, packaging/docker-builder/README.md
See #12 
Just a small image based on `maven:3.5.0-jdk-8`. With the current setup it can be used by both Cloud Plugins and Docker Pipeline if needed.
@reviewbybees @jglick @carlossg
=> Fix #12 - Add a Docker Image which bundles tools Required by Custom WAR Packager

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/Config.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/EssentialsYMLConfig.java
With this patch Custom WAR Packager implements custom handling of files named as `essentials.yml`, so that it simplifies local testing of the packaging flow.
Example:
```
mvn io.jenkins.tools.custom-war-packager:custom-war-packager-maven-plugin:0.1-alpha-6-SNAPSHOT:custom-war -DconfigFile=essentials.yml
```
@reviewbybees @raul-arabaolaza
=> [JENKINS-51213] - Add support of Essentials.yml to Custom WAR Packager

custom-war-packager-maven-plugin/pom.xml, custom-war-packager-maven-plugin/src/main/java/io/jenkins/tools/warpackager/mavenplugin/BuildMojo.java, custom-war-packager-maven-plugin/src/main/java/io/jenkins/tools/warpackager/mavenplugin/PackageMojo.java
Also allows passing installArtifacts which is helpful in this mode
Example:
```
mvn io.jenkins.tools.custom-war-packager:custom-war-packager-maven-plugin:0.1-alpha-6-SNAPSHOT:build -DconfigFile=essentials.yml
```
@reviewbybees @raul-arabaolaza
=> [JENKINS-51214] - Allow invoking Custom WAR Packager Maven Plugin in the CLI Mode

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/BuildSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/DockerBuildSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/DockerfileBuilder.java, custom-war-packager-maven-plugin/src/it/spotcheck/spotcheck.yml, demo/all-latest-core/README.md, demo/all-latest-core/packager-config.yml, demo/external-logging-elasticsearch/packager-config.yml
This change allows generating Dockerfiles in the output directory, so anybody can quickly build Docker image and run it. Demos are also updated.
```yml
buildSettings:
docker:
base: "jenkins/jenkins:2.107.3"
tag: "jenkins/demo-external-task-logging-logstash"
build: true
```
Questions to reviewers:
* Do we need to enable building of Docker images? Not needed for CI flows where I would rather use Docker Pipeline plugin with proper configuration => *ADDED*
* If we agree that the build is needed, should it be triggered by setting a `tag` argument? Or would you like to have a more complex flow
https://issues.jenkins-ci.org/browse/JENKINS-51067
@reviewbybees @jglick @raul-arabaolaza @carlossg
=> [JENKINS-51067] - Support generation of Dockerfile for the build

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/JenkinsWarPatcher.java
After the change we will have 2 POMs in resources: one for "jenkins-war" and another one for the artifact ID defined in Custom WAR Packager settings. If CWP defines "org.jenkins-ci.main:jenkins-war", the pom.xml will be just overridden hence there is no compatibility issues with existing demos.
https://issues.jenkins-ci.org/browse/JENKINS-51302
@reviewbybees @raul-arabaolaza @jglick
=> [JENKINS-51302] - Properly cleanup Metadata so that PCT does not miss metadata for running integration tests

README.md, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/CasCConfig.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/Config.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/GroovyHookInfo.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/WARResourceInfo.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/BOMBuilder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/JenkinsWarPatcher.java, demo/casc/Makefile, demo/casc/README.md, demo/casc/casc.yml, demo/casc/packager-config.yml
Reference implementation for https://github.com/jenkinsci/configuration-as-code-plugin/issues/249 , which can be used for Configuration-as-Code plugin testing within the Essentials test flow later.
See the demo for configuration examples. Depends on https://github.com/jenkinsci/configuration-as-code-plugin/pull/250
https://issues.jenkins-ci.org/browse/JENKINS-51656
@reviewbybees @raul-arabaolaza @MadsNielsen @ewelinawilkosz @ndeloof
=> [JENKINS-51656] - Add support of Configuration-as-Code Plugin to Custom WAR Packager

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/Config.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/LibraryInfo.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/WarInfo.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/model/bom/ComponentReference.java, demo/stapler/README.md, demo/stapler/build.sh, demo/stapler/packager-config.yml
See the new Stapler demo for an example, in some cases you need to use a property to update libraries (like the case of Stapler) and build war file.
=> Add support to core libraries that need a rebuild of war file

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/BuildSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/DependencyBuildSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/JenkinsfileRunnerSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/BOMBuilder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/JenkinsDockerfileBuilder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/jenkinsfileRunner/JenkinsfileRunnerDockerBuilder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/model/bom/ComponentReference.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/DockerfileBuilder.java, demo/jenkinsfile-runner/Jenkinsfile, demo/jenkinsfile-runner/Makefile, demo/jenkinsfile-runner/README.md, demo/jenkinsfile-runner/casc.yml, demo/jenkinsfile-runner/init.groovy, demo/jenkinsfile-runner/packager-config.yml
Just a hackish prototype I assembled on the weekend. It allows to package arbitrary plugins, JCasC settings and groovy scripts... using a single YAML definition. Both utility packaging and Docker image build are supported
Demo: https://github.com/oleg-nenashev/custom-war-packager/tree/jenkinsfileRunnerDemo/demo/jenkinsfile-runner 
```
docker run --rm -v $PWD/Jenkinsfile:/workspace/Jenkinsfile jenkins-experimental/cwp-jenkinsfile-runner-demo
```
```yaml
bundle:
groupId: "io.jenkins.tools.custom-war-packager.demo"
artifactId: "jenkinsfile-runner"
vendor: "Jenkins project"
title: "Jenkinsfile Runner demo"
description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"
buildSettings:
jenkinsfileRunner:
source:
groupId: "io.jenkins"
artifactId: "jenkinsfile-runner"
build: …
```
=> Add support of Jenkinsfile Runner docker image packaging

README.md
The PR simplifies the description of CWP and adds a link to https://jenkins.io/blog/2018/10/16/custom-war-packager/
=> Update readme: Better tool overview

demo/external-logging-elasticsearch/packager-config.yml
Some bits got integrated, and @jglick removed branches. Although the demo is still behind the final code versions and need update to External Logging for Elasticsearch plugin, this change at least makes the demo runnable at least.
CC @jglick @raul-arabaolaza
=> Update External Logging demo plugin deps.

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/SystemCommandHelper.java
Without these changes, any attempts to use this on Windows would yield:
```
Exception in thread "main" java.io.IOException: Cannot run program "mvn" (in directory "tmp\hpiDownloads"): CreateProcess error=2, The system cannot find the file specified
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at io.jenkins.tools.warpackager.lib.util.SystemCommandHelper.runFor(SystemCommandHelper.java:29)
at io.jenkins.tools.warpackager.lib.util.SystemCommandHelper.processFor(SystemCommandHelper.java:20)
at io.jenkins.tools.warpackager.lib.util.MavenHelper.run(MavenHelper.java:60)
at io.jenkins.tools.warpackager.lib.util.MavenHelper.listDependenciesFromPom(MavenHelper.java:95)
at io.jenkins.tools.warpackager.lib.config.Config.overrideByPOM(Config.java:193)
at …
```
=> feat: add Windows support

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, custom-war-packager-maven-plugin/src/it/bom/bom.yml, custom-war-packager-maven-plugin/src/it/bom/config.yml, custom-war-packager-maven-plugin/src/it/casc/bom.yml, custom-war-packager-maven-plugin/src/it/casc/casc.yml, custom-war-packager-maven-plugin/src/it/casc/config.yml, custom-war-packager-maven-plugin/src/it/casc/invoker.properties, custom-war-packager-maven-plugin/src/it/casc/pom.xml, custom-war-packager-maven-plugin/src/it/spotcheck/spotcheck.yml
I am developing a `ci.jenkins.io-runner` to simplify development of Jenkins Pipeline library. To simplify upper bounds checks, I want to use pom.xml as an input. And hence I hit https://issues.jenkins-ci.org/browse/JENKINS-54340
The PR also fixes some tests which are currently broken
@varyvol @fcojfernandez @raul-arabaolaza
=> [JENKINS-54340] - Support defining JCasC plugin in BOM and pom.xml

demo/artifact-manager-s3-pom/pom.xml
Not sure it is desired/needed, but filing just in case as I'm updating things to use this new version that support JDK 11 bytecode.
=> Bump to extra-enforcer-rules 1.1

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/BuildSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/Config.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java
Background
----------
For about a year now, we've maintained a `pom.xml` for our Global Pipeline Library project, allowing us to write unit and integration tests, write strongly-typed code that uses plugins, allow us to dive into the source code of our dependencies, etc.  When I saw that the custom-war-packager had support for POM files, I jumped on the chance to unify the dependencies for our Jenkins instance and for our Global Pipeline Library by defining the dependencies for both in a single file.
Then I discovered the that the POM support was meant for integration testing of Jenkins plugins themselves....unless I add a small feature for turning off the default behavior and not attempt to add the artifact defined by the POM if the configuration says so.  This is what this PR does. …
=> feat: Add support for non-plugin POM

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java
I was tired of waiting 4-5 seconds for each of the 292 dependencies detected by Maven every time I ran the CWP, so I decided to add a mechanism by which we remember dependencies that didn't exist as HPIs, with the ability to invalidate the cache by deleting one or more folders.  While doing so, I discovered that `~` isn't actually interpreted by the `File` class with either of Oracle JDK 1.8.0_171 on Windows nor OpenJDK 1.8.0_171 on CentOS, so I fixed that, too.
This pull request builds on top of #50 because it's kind of hard to keep adding features and run the debugger without Windows support.  Once #50 is merged, I can rebase this branch.
Manual testing
==============
Without these changes:
1. A sub-tree called `~/.m2/repository` under the current directory was checked by …
=> feat: cache non-HPI dependencies

jenkinsfile-runner-tests/Makefile, jenkinsfile-runner-tests/test_resources/test_cwp_casc_simple/Jenkinsfile, jenkinsfile-runner-tests/test_resources/test_cwp_casc_simple/casc.yml, jenkinsfile-runner-tests/test_resources/test_cwp_casc_simple/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_casc_with_pipeline_library/Jenkinsfile, jenkinsfile-runner-tests/test_resources/test_cwp_casc_with_pipeline_library/casc.yml, jenkinsfile-runner-tests/test_resources/test_cwp_casc_with_pipeline_library/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_casc_with_tool/Jenkinsfile, jenkinsfile-runner-tests/test_resources/test_cwp_casc_with_tool/casc.yml, jenkinsfile-runner-tests/test_resources/test_cwp_casc_with_tool/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_with_groovy_hooks/Jenkinsfile, jenkinsfile-runner-tests/test_resources/test_cwp_with_groovy_hooks/init.groovy, jenkinsfile-runner-tests/test_resources/test_cwp_with_groovy_hooks/packager-config.yml, jenkinsfile-runner-tests/tests.sh
This PR adds the following basic test cases of building Jenkinsfile-runner with the custom-war-packager
1. A simple build using Jenkins Configuration as Code.  This just verifies that the system message was set correctly.
2. Use JCasC to configure a tool, in this case maven.
3. Use JCasC to configure a global library
4. Use a groovy hook.
=> [JENKINS-54352] Add initial tests of building Jenkinsfile-runner with CWP

.gitignore, Jenkinsfile, README.md, custom-war-packager-cli/src/main/java/io/jenkins/tools/warpackager/cli/Main.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/Config.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/DependencyInfo.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java, custom-war-packager-maven-plugin/src/it/bom/config.yml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/packager-config-with-dependency.yml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/packager-config-with-property.yml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/packager-config-with-war-property.yml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/pom-with-dependency.xml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/pom-with-property.xml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/pom-with-war-property.xml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/pom.xml, jenkinsfile-runner-tests/test_resources/test_war_not_from_pom/packager-config-with-dependency.yml, jenkinsfile-runner-tests/test_resources/test_war_not_from_pom/packager-config-with-property.yml, jenkinsfile-runner-tests/test_resources/test_war_not_from_pom/packager-config-with-war-property.yml, jenkinsfile-runner-tests/test_resources/test_war_not_from_pom/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_war_not_from_pom/pom-with-dependency.xml, jenkinsfile-runner-tests/test_resources/test_war_not_from_pom/pom-with-property.xml, jenkinsfile-runner-tests/test_resources/test_war_not_from_pom/pom-with-war-property.xml, jenkinsfile-runner-tests/test_resources/test_war_not_from_pom/pom.xml, jenkinsfile-runner-tests/tests.sh
See [JENKINS-55568](https://issues.jenkins-ci.org/browse/JENKINS-55568)
Add support of passing Jenkins Core version from pom.xml:
- In case the `jenkins.version` is specified, the war section in yml file is overridden and ignored 
- In case a dependency on `jenkins-core` or `jenkins-war` exist, the dependency overrides any other configuration for the core.
Besides, the documentation is updated and I've added a test.
=> [JENKINS-55568] Add support of passing Jenkins Core version from pom.xml

.github/release-drafter.yml, pom.xml
This change should remove the odd `parent-pom-$version` scheme and to offer something more convenient for GitHub users and for deployments to DockerHub.
=> Change the version tag format to `v${VERSION}`

README.md, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/BuildSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/Config.java, demo/artifact-manager-s3-pom/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/packager-config-with-dependency.yml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/packager-config-with-property.yml, jenkinsfile-runner-tests/test_resources/test_war_from_pom/packager-config-with-war-property.yml
This is a first baby step towards reorganizing the YAML configuration. Using top level was a mistake historically, and I would not like to carry it over to 2.0
=> Move bomIncludeWAR to buildSettings, split out pomIncludeWAR to a separate setting (breaking change)

LICENSE.md
Addresses https://github.com/jenkinsci/custom-war-packager/issues/116 . Before the change the license was defined in pom.xml only
=> Add an explicit MIT license to the repository

pom.xml
Jenkins Parent POM 1.41+ provides JUnit version: https://github.com/jenkinsci/pom/pull/19 . There is no need to hardcode it here
=> Use JUnit version supplied by Jenkins Parent POM
