Jenkinsfile
Fixes #3 . Just a copy-paste of what I did for https://github.com/jenkinsci/plugin-compat-tester/blob/master/Jenkinsfile, but with enabled integration tests
Hosting request: https://issues.jenkins-ci.org/browse/INFRA-1559
=> Issue #3 - Create Jenkinsfile

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/DependencyBuildSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/DependencyInfo.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, demo/all-latest-core/build.sh, demo/external-logging-elasticsearch/build.sh, demo/external-logging-elasticsearch/packager-config.yml
Now it builds twice faster on common scenarios when cache is missing
@reviewbybees
=> Fix #10. Building original SNAPSHOTs is now opt-in to speedup builds

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java
Required for https://github.com/jenkinsci/remoting/pull/265
@reviewbybees
=> Add support of directory as a build source for plugins and libs

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/JenkinsWarPatcher.java
I am experimenting with a Jenkins WAR file, which applies web.xml patches to change appearance of the instance. Currently CWP rewrites web.xml even if there is no changes, and it breaks the patches. So it makes sense to just copy the resource when there is no changes to be applied.
P.S: I will modify CWP later to make appearances editable as well
@reviewbybees @raul-arabaolaza
=> Do not rewrite web.xml when there is no changes

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/MavenHPICustomWARPOMGenerator.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/MavenWARPackagePOMGenerator.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/POMGenerator.java, custom-war-packager-maven-plugin/src/it/incrementals/config.yml, custom-war-packager-maven-plugin/src/it/incrementals/invoker.properties, custom-war-packager-maven-plugin/src/it/incrementals/pom.xml
This patch enables building with versions from the incrementals repository. [JENKINS-51094](https://issues.jenkins-ci.org/browse/JENKINS-51094) is an advanced feature, which should allow taking **latest** releases from incrementals to enable rolling releases where needed.
https://issues.jenkins-ci.org/browse/JENKINS-51093
@reviewbybees @jglick @raul-arabaolaza
=> [JENKINS-51093] - Add support of artifacts from Incrementals repo (JEP-305)

custom-war-packager-cli/src/main/java/io/jenkins/tools/warpackager/cli/CliOptions.java, custom-war-packager-cli/src/main/java/io/jenkins/tools/warpackager/cli/Main.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/BuildSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/Config.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/PackageInfo.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/SourceInfo.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/BOMBuilder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/model/bom/BOM.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/model/bom/ComponentReference.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/model/bom/Environment.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/model/bom/Metadata.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/model/bom/Reference.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/model/bom/Specification.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/CollectionsHelper.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/SimpleManifest.java, custom-war-packager-lib/src/test/java/io/jenkins/tools/warpackager/lib/model/bom/BOMTest.java, custom-war-packager-lib/src/test/resources/io/jenkins/tools/warpackager/lib/model/bom/BOM.yml, custom-war-packager-maven-plugin/src/it/bom/bom.yml, custom-war-packager-maven-plugin/src/it/bom/config.yml, custom-war-packager-maven-plugin/src/it/bom/invoker.properties, custom-war-packager-maven-plugin/src/it/bom/pom.xml, custom-war-packager-maven-plugin/src/main/java/io/jenkins/tools/warpackager/mavenplugin/PackageMojo.java
This is a reference implementation for https://github.com/jenkinsci/jep/pull/92
https://issues.jenkins-ci.org/browse/JENKINS-51077
@reviewbybees @carlossg @raul-arabaolaza
=> [JENKINS-51077] - BOM Support in Custom WAR Packager

custom-war-packager-cli/src/main/java/io/jenkins/tools/warpackager/cli/CliOptions.java, custom-war-packager-cli/src/main/java/io/jenkins/tools/warpackager/cli/Main.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/BuildSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/MavenWARPackagePOMGenerator.java
https://issues.jenkins-ci.org/browse/JENKINS-51112
@reviewbybees
=> [JENKINS-51112] - Add support of installing WAR locally in the CLI mode

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/model/bom/ComponentReference.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/model/bom/Reference.java
Required for https://github.com/jenkinsci/artifact-manager-s3-plugin/pull/20
As discussed with @carlossg, he is ready to add it to BOM if needed.
@reviewbybees @carlossg @raul-arabaolaza
=> [JENKINS-51183] - Support Directory references in BOM

README.md
Just noticed a small difference while running the tool locally via CLI.
=> Update output file path in README.md

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/DockerBuildSettings.java
* customSettings field to store (or whatever you want)
* A boolean field to enable push
* A String field to store the registry URL (http://docker.io)
* A String field to store the credentials Id on Jenkins
@oleg-nenashev
=> add some fields to grab the info need to push the Docker image to a registry

README.md
Addressed comment from @carlossg in the private discussion
=> Update the BOM example

CHANGELOG.md, README.md
Integrates #40 and adds some disclaimers
CC @carlossg @jglick @raul-arabaolaza
=> Changelog towards 1.2

CHANGELOG.md, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/jenkinsfileRunner/JenkinsfileRunnerDockerBuilder.java, custom-war-packager-lib/src/main/resources/io/jenkins/tools/warpackager/lib/config/sample.yml, demo/casc/Makefile, demo/casc/casc.yml, demo/casc/packager-config.yml, demo/jenkinsfile-runner/Makefile, demo/jenkinsfile-runner/packager-config.yml
FYI @jglick 
Once the incrementals is ready, we can use this branch to verify the fix
=> [JENKINS-54151] - Fix compatibility with JCasC 1.0, drop support of pre-release versions

Dockerfile
=> Dockerfile: Replace CMD by ENTRYPOINT

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java
=> Fix the Maven-in-Maven call on Windows"

custom-war-packager-maven-plugin/src/main/java/io/jenkins/tools/warpackager/mavenplugin/BuildMojo.java
Latest Maven release for the Maven plugin is missing due to this issue
CC @raul-arabaolaza
=> Fix broken Javadoc which was breaking the Maven plugin release

README.md, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/BuildSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/Config.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java
Polishes #52 from @olivierdagenais
=> Polish #52 - Rename the argument and invert the logic + docs

.gitignore, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, demo/jenkinsfile-runner/packager-config.yml
[JENKINS-54375](https://issues.jenkins-ci.org/browse/JENKINS-54375)
Once JFR has been released, we can use the tag on the demo.
@oleg-nenashev @raul-arabaolaza @fcojfernandez
=> [JENKINS-54375] Use JFR tag instead of commit

.gitignore, jenkinsfile-runner-tests/test_resources/test_cwp_casc_simple/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_casc_with_tool/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_classloading/Jenkinsfile, jenkinsfile-runner-tests/test_resources/test_cwp_classloading/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_commit/Jenkinsfile, jenkinsfile-runner-tests/test_resources/test_cwp_commit/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_jfr/Jenkinsfile, jenkinsfile-runner-tests/test_resources/test_cwp_jfr/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_with_groovy_hooks/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_workspace/Jenkinsfile, jenkinsfile-runner-tests/test_resources/test_cwp_workspace/packager-config.yml, jenkinsfile-runner-tests/tests.sh
[JENKINS-54352](https://issues.jenkins-ci.org/browse/JENKINS-54352)
Tests:
- That a standard JFR generated image executes properly.
- That a JFR generated image can interact with the workspace.
- That a JFR image can be generated specifying specific commits for plugins.
- That classloading happens as expected.
=> [JENKINS-54352] Automated tests for CWP generated JFR images

README.md, custom-war-packager-cli/src/main/java/io/jenkins/tools/warpackager/cli/CliOptions.java, custom-war-packager-cli/src/main/java/io/jenkins/tools/warpackager/cli/Main.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/config/JenkinsfileRunnerSettings.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/jenkinsfileRunner/JenkinsfileRunnerDockerBuilder.java, jenkinsfile-runner-tests/test_resources/test_cwp_casc_with_pipeline_library/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_sandbox_configuration/Jenkinsfile, jenkinsfile-runner-tests/test_resources/test_cwp_sandbox_configuration/packager-config.yml, jenkinsfile-runner-tests/test_resources/test_cwp_workspace_non_default/Jenkinsfile, jenkinsfile-runner-tests/test_resources/test_cwp_workspace_non_default/packager-config.yml, jenkinsfile-runner-tests/tests.sh
[JENKINS-55703](https://issues.jenkins-ci.org/browse/JENKINS-55703)
Given Jenkinsfile-Runner allow both options now, Custom War Packager should allow providing them through CLI options so that the generated JFR image works like that.
Automated test to como in a follow up PR.
=> [JENKINS-55703] Allow specifying --runWorkspace and --no-sandbox options

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/MavenWARPackagePOMGenerator.java
This change might fix issue #66, if it is really an issue and not wrong usage of the tool.
=> Fixes #66 "Error assembling WAR: webxml attribute is required"

CHANGELOG.md
Version 1.6 is missing in CHANGELOG.md
=> Add release 1.6 to Changelog

.github/release-drafter.yml
See https://groups.google.com/forum/#!topic/jenkinsci-dev/dOs8YRQwQiI and https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml for the base configuration
=> Create the initial Release Drafter configuration

.dockerignore, .gitignore
Subj. Also speeds up the Docker build a bit
=> Update .gitignore and .dockerignore to properly ignore IDEs and integration tests

README.md
Preview: https://github.com/jenkinsci/custom-war-packager/blob/versions/README.md
=> Add explicit disclaimer for the 2.0 Alpha release documentation

README.md
I'm not sure it's suitable putting it into here. But it could be a good idea about how to use this project.
=> Add a cwp demo link

.github/dependabot.yml
=> Switch to GitHub-native Dependabot

custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/Builder.java, custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/impl/jenkinsfileRunner/JenkinsfileRunnerDockerBuilder.java, demo/jenkinsfile-runner/Makefile, demo/jenkinsfile-runner/casc.yml, demo/jenkinsfile-runner/demo/Jenkinsfile, demo/jenkinsfile-runner/packager-config.yml
This change aligns Custom WAR Packager with recent Jenkinsfile Runner changes and includes a few performance and Docker image size improvements
=> Improve error message when Git tag or branch cannot be found + Update Jenkinsfile Runner Demo

ROADMAP.adoc
Documents notes from https://groups.google.com/g/jenkinsci-dev/c/iM70YT_g6OE/m/zn2-kzAJAwAJ and references new projects related to Custom WAR Packager. CC @sladyn98 @waveywaves
=> Add Custom WAR Packager Roadmap

custom-war-packager-lib/pom.xml
=> Update Jackson Databind to 2.11.2

Jenkinsfile
The destination file has changed after the migration to SpotBugs
=> Fix SpotBugs reporting in Jenkinsfile
